# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/angel/Proyecto_integrador/ProyectoGym

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/angel/Proyecto_integrador/ProyectoGym

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/angel/Proyecto_integrador/ProyectoGym/CMakeFiles /home/angel/Proyecto_integrador/ProyectoGym//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/angel/Proyecto_integrador/ProyectoGym/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GymApp

# Build rule for target.
GymApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GymApp
.PHONY : GymApp

# fast build rule for target.
GymApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/build
.PHONY : GymApp/fast

#=============================================================================
# Target rules for targets named GymApp_autogen_timestamp_deps

# Build rule for target.
GymApp_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GymApp_autogen_timestamp_deps
.PHONY : GymApp_autogen_timestamp_deps

# fast build rule for target.
GymApp_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp_autogen_timestamp_deps.dir/build.make CMakeFiles/GymApp_autogen_timestamp_deps.dir/build
.PHONY : GymApp_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named GymApp_autogen

# Build rule for target.
GymApp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GymApp_autogen
.PHONY : GymApp_autogen

# fast build rule for target.
GymApp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp_autogen.dir/build.make CMakeFiles/GymApp_autogen.dir/build
.PHONY : GymApp_autogen/fast

GymApp_autogen/mocs_compilation.o: GymApp_autogen/mocs_compilation.cpp.o
.PHONY : GymApp_autogen/mocs_compilation.o

# target to build an object file
GymApp_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/GymApp_autogen/mocs_compilation.cpp.o
.PHONY : GymApp_autogen/mocs_compilation.cpp.o

GymApp_autogen/mocs_compilation.i: GymApp_autogen/mocs_compilation.cpp.i
.PHONY : GymApp_autogen/mocs_compilation.i

# target to preprocess a source file
GymApp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/GymApp_autogen/mocs_compilation.cpp.i
.PHONY : GymApp_autogen/mocs_compilation.cpp.i

GymApp_autogen/mocs_compilation.s: GymApp_autogen/mocs_compilation.cpp.s
.PHONY : GymApp_autogen/mocs_compilation.s

# target to generate assembly for a file
GymApp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/GymApp_autogen/mocs_compilation.cpp.s
.PHONY : GymApp_autogen/mocs_compilation.cpp.s

database.o: database.cpp.o
.PHONY : database.o

# target to build an object file
database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/database.cpp.o
.PHONY : database.cpp.o

database.i: database.cpp.i
.PHONY : database.i

# target to preprocess a source file
database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/database.cpp.i
.PHONY : database.cpp.i

database.s: database.cpp.s
.PHONY : database.s

# target to generate assembly for a file
database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/database.cpp.s
.PHONY : database.cpp.s

loginwindow.o: loginwindow.cpp.o
.PHONY : loginwindow.o

# target to build an object file
loginwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/loginwindow.cpp.o
.PHONY : loginwindow.cpp.o

loginwindow.i: loginwindow.cpp.i
.PHONY : loginwindow.i

# target to preprocess a source file
loginwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/loginwindow.cpp.i
.PHONY : loginwindow.cpp.i

loginwindow.s: loginwindow.cpp.s
.PHONY : loginwindow.s

# target to generate assembly for a file
loginwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/loginwindow.cpp.s
.PHONY : loginwindow.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

registerwindow.o: registerwindow.cpp.o
.PHONY : registerwindow.o

# target to build an object file
registerwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/registerwindow.cpp.o
.PHONY : registerwindow.cpp.o

registerwindow.i: registerwindow.cpp.i
.PHONY : registerwindow.i

# target to preprocess a source file
registerwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/registerwindow.cpp.i
.PHONY : registerwindow.cpp.i

registerwindow.s: registerwindow.cpp.s
.PHONY : registerwindow.s

# target to generate assembly for a file
registerwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/registerwindow.cpp.s
.PHONY : registerwindow.cpp.s

rutinagenerator.o: rutinagenerator.cpp.o
.PHONY : rutinagenerator.o

# target to build an object file
rutinagenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/rutinagenerator.cpp.o
.PHONY : rutinagenerator.cpp.o

rutinagenerator.i: rutinagenerator.cpp.i
.PHONY : rutinagenerator.i

# target to preprocess a source file
rutinagenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/rutinagenerator.cpp.i
.PHONY : rutinagenerator.cpp.i

rutinagenerator.s: rutinagenerator.cpp.s
.PHONY : rutinagenerator.s

# target to generate assembly for a file
rutinagenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/rutinagenerator.cpp.s
.PHONY : rutinagenerator.cpp.s

rutinaswindow.o: rutinaswindow.cpp.o
.PHONY : rutinaswindow.o

# target to build an object file
rutinaswindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/rutinaswindow.cpp.o
.PHONY : rutinaswindow.cpp.o

rutinaswindow.i: rutinaswindow.cpp.i
.PHONY : rutinaswindow.i

# target to preprocess a source file
rutinaswindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/rutinaswindow.cpp.i
.PHONY : rutinaswindow.cpp.i

rutinaswindow.s: rutinaswindow.cpp.s
.PHONY : rutinaswindow.s

# target to generate assembly for a file
rutinaswindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GymApp.dir/build.make CMakeFiles/GymApp.dir/rutinaswindow.cpp.s
.PHONY : rutinaswindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GymApp_autogen"
	@echo "... GymApp_autogen_timestamp_deps"
	@echo "... GymApp"
	@echo "... GymApp_autogen/mocs_compilation.o"
	@echo "... GymApp_autogen/mocs_compilation.i"
	@echo "... GymApp_autogen/mocs_compilation.s"
	@echo "... database.o"
	@echo "... database.i"
	@echo "... database.s"
	@echo "... loginwindow.o"
	@echo "... loginwindow.i"
	@echo "... loginwindow.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... registerwindow.o"
	@echo "... registerwindow.i"
	@echo "... registerwindow.s"
	@echo "... rutinagenerator.o"
	@echo "... rutinagenerator.i"
	@echo "... rutinagenerator.s"
	@echo "... rutinaswindow.o"
	@echo "... rutinaswindow.i"
	@echo "... rutinaswindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

